### DISCUSSION TITLE
Have I misunderstood the functionality or why are there no hello.txt/goodbye.txt in dist/*.whl?

### DISCUSSION THREAD

**Discussion by lfvjimisola** [rmorshea/hatch-build-scripts#3] [Q&A]
Following the example in the README: https://github.com/rmorshea/hatch-build-scripts?tab=readme-ov-file#usage

Shall hello.txt and goodbye.txt not be included in the generated whl file under dist?

**Comment by lfvjimisola** [comment]
Also, I believe that this hatch build hook is to limited for our use case, but I just want to confirm.

The README example generates hello.txt and goodbye.txt to the top level directory and shows no example of how to control the directory structure.

This a our use-case:

```toml
[[tool.hatch.build.hooks.build-scripts.scripts]]
out_dir = "out"
commands = [
    mkdir tmp ; echo 'Hello, world!' > tmp/hello.txt",
]
artifacts = [
    "tmp/hello.txt"
]
```

This will copy the hello.txt artifact to `out/tmp/hello.txt`. Whereas I want it to be copied to `out/hello.txt`.
There could of course be users that have want to copy it flat or to just keep a certain part of the path, e.g.

command will generate: build/tmp/generated_src/<package>/files.1|directory/files.2 etc

I now want to move the entire generated structure to `generated_src/<package>/files.1|directory/files.2`.

Any thing that you might consider adding or do you think that this is out of the scope for this plugin?
